In [1]:
import numpy as np
import random
#================================== Define the maze layout ============================================
maze = np.array([
    [0, 0, 0, -1, 0],  # 0: free space, -1: obstacle, 1: goal
    [0, -1, 0, -1, 0],
    [0, 0, 0, 0, 0],
    [-1, 0, -1, 0, -1],
    [0, 0, 0, 1, 0]     # Goal is at (4, 3)
])
#================================= Define hyperparameters ==============================================
alpha = 0.1               # Learning rate
gamma = 0.9               # Discount factor
epsilon = 0.8             # Exploration rate
epsilon_decay = 0.995
num_episodes = 500
#=========================================== Define actions ============================================
actions = {
    0: (-1, 0),  # Up
    1: (1, 0),   # Down
    2: (0, -1),  # Left
    3: (0, 1)    # Right
}
#============================== Initialize Q-table with zeros (size of the maze x number of actions) ==========================================
no_rows, no_cols = maze.shape
q_table = np.zeros((no_rows, no_cols, 4))  # 4 possible actions (up, down, left, right)

#======================================== Define function to check if a position is valid =========================================
def is_valid_position(maze, position):
    x, y = position
    return 0 <= x < no_rows and 0 <= y < no_cols and maze[x, y] != -1

#======================================= Define function to get next position based on action ======================================
def get_next_position(position, action):
    x, y = position
    dx, dy = actions[action]
    next_position = (x + dx, y + dy)
    return next_position if is_valid_position(maze, next_position) else position
#===================================================== Define reward function ====================================================
def get_reward(position):
    if maze[position] == 1:
        return 10  # Goal reward
    elif maze[position] == -1:
        return -1  # Penalty for hitting an obstacle
    else:
        return -0.1  # Small penalty for each step taken
#====================================================== Q-learning algorithm ===================================================
for episode in range(num_episodes):
    position = (0, 0)  # Start position at top-left corner
    done = False
    while not done:
#==================== Choose action based on epsilon-greedy policy =============================
if random.uniform(0, 1) < epsilon:
    action = random.randint(0, 3)  # Explore: random action
else:
    action = np.argmax(q_table[position[0], position[1]])  # Exploit: best action
#======================================= Take action and observe next state and reward =====================================
next_position = get_next_position(position, action)
reward = get_reward(next_position)
#======================================== Update Q-value using Q-learning formula =========================================
q_table[position[0], position[1], action] += alpha * (reward + gamma * np.max(q_table[next_position[0], next_position[1]]) - q_table[position[0], position[1], action])

#============================================== Update position ================================================
position = next_position
#=========================================== Check if goal is reached =============================================
if maze[position] == 1:
    done = True
#======================================================= Decay epsilon to reduce exploration over time =================================
epsilon *= epsilon_decay
#======================================================= Display Final Q-table =================================================
print("Training completed!")
print("Final Q-table:")
print(q_table)


Training completed!
Final Q-table:
[[[ 3.74287202e+00  3.18415883e+00  3.97341650e+00  4.84585100e+00]
  [ 4.72644290e+00  4.68590322e+00  3.93199106e+00  5.49539000e+00]
  [ 5.46451459e+00  6.21710000e+00  4.77270767e+00  5.41097649e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [-1.90000000e-02 -2.83176525e-02 -2.96200000e-02 -2.88100000e-02]]

 [[ 2.10404084e+00  4.64865355e+00  1.05204157e-01  3.09332476e-01]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [ 5.39923613e+00  7.01900000e+00  6.09834463e+00  6.15568341e+00]
  [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
  [-3.69100000e-02  3.24316969e+00 -3.61000000e-02 -1.99000000e-02]]

 [[ 4.36577909e-01  1.41436858e+00  8.11414255e-01  6.00062355e+00]
  [ 3.91832800e+00  9.60010065e-01  1.88082150e+00  7.01492129e+00]
  [ 6.18027338e+00  7.00026282e+00  6.07711998e+00  7.91000000e+00]
  [ 7.86548128e+00  8.90000000e+00  6.98130116e+00  6.70244902e+00]
  [ 7.110